image: ubuntu:jammy

stages:
  - test
  - deploy
  - release

test:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
    - echo "tzdata tzdata/Areas select Europe" > preseed.txt && echo "tzdata tzdata/Zones/Europe select Paris" >> preseed.txt
    - debconf-set-selections preseed.txt
    - apt-get update --allow-releaseinfo-change && apt-get install -yqq --no-install-recommends python3-pip python3-dev python3-venv graphviz libblas-dev liblapack-dev cmake gfortran gcc g++ make libproj-dev proj-data proj-bin libgeos-dev curl
    - python3 --version
    - pip3 install pdm
    - pdm install
    - SETUPTOOLS_SCM_PRETEND_VERSION=0.0.1 pdm build
    - SETUPTOOLS_SCM_PRETEND_VERSION=0.0.1 pdm doc
    - SETUPTOOLS_SCM_PRETEND_VERSION=0.0.1 pdm run pytest
  artifacts:
    when: always
    paths:
      - build/htmldoc

# https://ydethe.gitlab.io/network/htmldoc/network/
pages:
  stage: deploy
  dependencies:
  - test
  script:
    - cp -r build/htmldoc public
  artifacts:
    paths:
      - public
