version: "3.4"

services:
  network:
    image: network:latest
    ports:
      - "3034:3034"
    environment:
      ROOT_PATH: /v1
      DATABASE_URI: postgresql+psycopg2://network:network@localhost/network
      HOST: https://network.johncloud.fr
      NB_WORKERS: 4
      PORT: 3034
    network_mode: host
  # db:
  #   image: postgres:11.3
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USER:-baserow}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
  #     - POSTGRES_DB=${DATABASE_NAME:-baserow}
  #   healthcheck:
  #     test: [ "CMD-SHELL", "su postgres -c \"pg_isready -U ${DATABASE_USER:-baserow}\"" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   network_mode: host
# volumes:
#   pgdata:
